name: build-gnome-stats-pro2
on:
  push:
    paths:
      - "**/**.ts"
    branches:
      - '*'
    tags:
      - ci-test
  
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        cache: npm
    
    - run: npm install
    - run: npm ci
    - name: Compile
      shell: bash
      run: |
        npm run compile
